# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GcpExporter
                                 A QGIS plugin
 Exports GCPs from the QGIS canvas
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-09-14
        copyright            : (C) 2021 by Kartoza
        email                : divan@kartoza.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GcpExporter class from file GcpExporter.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .gcp_exporter import GcpExporter
    return GcpExporter(iface)
